tab_bar_edge            bottom
tab_bar_style           fade
tab_powerline_style     slanted
tab_bar_align           left
tab_bar_min_tabs        2
tab_bar_margin_width    0.0
tab_bar_margin_height   1.0 0.5
tab_fade                1
tab_bar_margin_color    #101418

tab_bar_background              #101418

active_tab_foreground           #cfe5ff
active_tab_background           #124a73
active_tab_font_style           bold

inactive_tab_foreground         #c2c7cf
inactive_tab_background         #101418
inactive_tab_font_style         normal

tab_activity_symbol             "●"
bell_on_tab none
tab_numbers_style               1

tab_title_template              "[{index}] {fmt.fg.red}{activity_symbol} {fmt.fg.tab}{(fmt.fg.color2 + chr(0xe6ae) if tab.active_exe in ('nvim', 'neovim') else fmt.fg.color2 + chr(0xe62b) if tab.active_exe in ('vim', 'vi', 'view') else fmt.fg.color4 + chr(0xe6b9) if tab.active_exe == 'zsh' else fmt.fg.color4 + chr(0xe760) if tab.active_exe in ('bash', 'sh') else fmt.fg.color4 + chr(0xee41) if tab.active_exe == 'fish' else fmt.fg.color1 + chr(0xe8b1) if tab.active_exe == 'ssh' else fmt.fg.color5 + chr(0xe94c) if tab.active_exe == 'tmux' else fmt.fg.color3 + chr(0xe73c) if 'python' in tab.active_exe else fmt.fg.color2 + chr(0xe718) if tab.active_exe == 'node' else fmt.fg._ff8700 + chr(0xe68b) if tab.active_exe in ('rustc', 'cargo') else fmt.fg.color6 + chr(0xe650) if tab.active_exe == 'docker' else chr(0xf120))}{fmt.fg.tab} {(tab.active_wd.rsplit('/', 1)[-1] or title or '/')[:25]}"
active_tab_title_template       "[{index}] {fmt.fg.red}{activity_symbol} {fmt.fg.tab}{(fmt.fg.color2 + chr(0xe6ae) if tab.active_exe in ('nvim', 'neovim') else fmt.fg.color2 + chr(0xe62b) if tab.active_exe in ('vim', 'vi', 'view') else fmt.fg.color4 + chr(0xe6b9) if tab.active_exe == 'zsh' else fmt.fg.color4 + chr(0xe760) if tab.active_exe in ('bash', 'sh') else fmt.fg.color4 + chr(0xee41) if tab.active_exe == 'fish' else fmt.fg.color1 + chr(0xe8b1) if tab.active_exe == 'ssh' else fmt.fg.color5 + chr(0xe94c) if tab.active_exe == 'tmux' else fmt.fg.color3 + chr(0xe73c) if 'python' in tab.active_exe else fmt.fg.color2 + chr(0xe718) if tab.active_exe == 'node' else fmt.fg._ff8700 + chr(0xe68b) if tab.active_exe in ('rustc', 'cargo') else fmt.fg.color6 + chr(0xe650) if tab.active_exe == 'docker' else chr(0xf120))}{fmt.fg.tab} {(tab.active_wd.rsplit('/', 1)[-1] or title or '/')[:25]}"
