-- Auto-generated by DMS Matugen hook — do not edit manually.
-- Remove require("dms.colors") from hyprland.lua to override.

hl.config({
	general = {
		col = {
			active_border = "rgb(bd93f9)",
			inactive_border = "rgb(6272a4)",
		},
	},
	group = {
		col = {
			border_active = "rgb(bd93f9)",
			border_inactive = "rgb(6272a4)",
			border_locked_active = "rgb(ff5555)",
			border_locked_inactive = "rgb(6272a4)",
		},
		groupbar = {
			col = {
				active = "rgb(bd93f9)",
				inactive = "rgb(6272a4)",
				locked_active = "rgb(ff5555)",
				locked_inactive = "rgb(6272a4)",
			},
		},
	},
})
