-- Auto-generated by DMS — do not edit manually

hl.monitor({ output = "eDP-1", mode = "2560x1600@240.000", position = "0x634", scale = 1.6015625, vrr = 0 })
hl.monitor({ output = "DP-2", mode = "2560x1440@280.099", position = "1600x634", scale = 1, vrr = 0 })
hl.monitor({ output = "DP-1", disabled = true })
